### ISSUE TITLE
Tileset exported

### ISSUE THREAD

**Issue by ajotanc** [4ian/GDevelop#4311]
Does anyone have this issue of tileset exported in Tiled to GDevelop? On Tiled it is correct, but when it goes to GDevelop it looks like this, is anyone having the same problem?

![Screenshot_1](https://user-images.githubusercontent.com/47322034/191387799-3c96e3ff-0d37-49f7-bd94-9169b3baeb1d.png)
![Screenshot_2](https://user-images.githubusercontent.com/47322034/191387804-d619ea27-4287-4891-9fc6-e2066420ee93.png)

**Comment by willianholtz** [comment]
are you exporting Image or using Tilemap (json)? If it's an image, I believe that when exporting, the grid is marked!

**Comment by ajotanc** [comment]
> are you exporting Image or using Tilemap (json)? If it's an image, I believe that when exporting, the grid is marked!
> 
> Edit: Ahh Sorry, I paid attention to the grids.. I think in the Tilemap you are using, it is like Index, leave it as All or visibles (if there is no layer on the tiled hidden)


I tried what you mentioned, but it still continues.. The tiles are like that because I used Tiled rotate, but in the previous version of GDevelop it was working correctly. After I updated the tiles I rotated are getting this way.

**Comment by 4ian** [comment]
@ajotanc Any chance you could share with us a minimal project showing the issue?
@D8H do you remember if there is a chance we messed up the tiles rotation during a refactoring?

**Comment by D8H** [comment]
Yes, there were a bug fix about flipping/rotation on the collision layer object. It's probably either a regression from the fix or the refactoring.

**Comment by ajotanc** [comment]
> Yes, there were a bug fix about flipping/rotation on the collision layer object. It's probably either a regression from the fix or the refactoring.
> Which version of GDevelop is used?

Yesterday I updated to 5.0.143 and this problem started, I updated to 5.0.144 and it still persists. The version which was working correctly was 5.0.142.

**Comment by ajotanc** [comment]
Follows prints as a better example.
![Screenshot_1](https://user-images.githubusercontent.com/47322034/191513905-338e94b7-4e75-4b2a-a2e6-7ab7ff6b4742.png)
![Screenshot_3](https://user-images.githubusercontent.com/47322034/191513910-0d6dce78-1856-4e3e-8710-ec3202d5a1fc.png)

**Comment by ajotanc** [comment]
Follows prints as a better example.
![Screenshot_2](https://user-images.githubusercontent.com/47322034/191514038-c46f635b-d1a9-4ed6-b996-7a7bf209ad1e.png)
![Screenshot_3](https://user-images.githubusercontent.com/47322034/191514042-44685092-d465-4ca6-82ad-a941c83fc1fa.png)

**Comment by D8H** [comment]
I can reproduce the issue with the tile map I used for this bugfix:
https://github.com/4ian/GDevelop/pull/4181

It looks like the render no longer do any flipping. It's probably a regression from the Pixi extension update.

![image](https://user-images.githubusercontent.com/2611977/191519631-201c1651-34ac-42bb-a0e4-5e755e1799be.png)

**Comment by ajotanc** [comment]
> I can reproduce the issue with the tile map I used for this bugfix: #4181
> 
> It looks like the render no longer do any flipping. It's probably a regression from the Pixi extension update.
> 
> ![image](https://user-images.githubusercontent.com/2611977/191519631-201c1651-34ac-42bb-a0e4-5e755e1799be.png)

Affs, how boring! Just thinking about reworking the entire map where there is this inversion. The map has no less than 150 blocks. :(

**Comment by D8H** [comment]
> > I can reproduce the issue with the tile map I used for this bugfix: #4181
> > It looks like the render no longer do any flipping. It's probably a regression from the Pixi extension update.
> > ![image](https://user-images.githubusercontent.com/2611977/191519631-201c1651-34ac-42bb-a0e4-5e755e1799be.png)
> 
> Affs, how boring! Just thinking about reworking the entire map where there is this inversion. The map has no less than 150 blocks. :(

It should be fixed today.

**Comment by ajotanc** [comment]
Hope so! :')

**Comment by ajotanc** [comment]
@D8H 
Good night, how are you? Do you know when the fix will come out?

**Comment by ajotanc** [comment]
> In about 12 hours, I guess. Thank you for reporting it.

I really liked the library and what I find "wrong" I will try to report if I make sure it really is a bug.

You are beasts!
Ahh, I'm also a developer.

I'm using it to develop a game that will be my proposal, haha! So it has to be something perfect.

**Comment by ajotanc** [comment]
So, in parts it ended up solving the problem... But another one came up that must be doing the same as the tile did, in this case the Mask Collision is still getting inverted, I'll send example images, the tiles are now correctly, but the tile mask does not. I ended up finding out, because the character is going to be a little bigger and to rearrange the map I increased the current character to the same size and I ended up identifying that. I don't know if it makes sense, but I'll send an example image too.

![2](https://user-images.githubusercontent.com/47322034/191866243-7f14322b-6d95-49d0-bb76-6456adbe0bc6.png)
![3](https://user-images.githubusercontent.com/47322034/191866245-068e0193-bd6b-4a88-a613-007de0046e68.png)
![4](https://user-images.githubusercontent.com/47322034/191866247-2bdc1d45-7ff5-4743-aecf-e00e0efbd0dc.png)
![1](https://user-images.githubusercontent.com/47322034/191866249-8863257f-dd2c-4f46-94c0-6335d700b8aa.png)

**Comment by ajotanc** [comment]
@D8H I ended up coming back, huh?

**Comment by D8H** [comment]
I'm not sure to understand. Please can you do a short video with the player traversing the hitboxes?

**Comment by ajotanc** [comment]
> I'm not sure to understand. Please can you do a short video with the player going through the hitboxes?

How do I activate this hitbox with the tilemap mask collision, is it "debug mode"? If so, when I activate it, I can't get over it.

**Comment by ajotanc** [comment]
Vídeo.
https://user-images.githubusercontent.com/47322034/191868444-96fa670e-2380-4b91-bea8-8732a19d24ec.mp4

**Comment by ajotanc** [comment]
Character 32x48

https://user-images.githubusercontent.com/47322034/191868781-3736c978-3155-4fa4-b55d-4bffe4d60c84.mp4

**Comment by ajotanc** [comment]
@D8H I forgot to mention, in this case, this only happens when the tile is rotated, vertical/horizontal flip.

**Comment by D8H** [comment]
Just to be sure, does the collision mask object has a Platform behavior attach to it?

**Comment by ajotanc** [comment]
> Just to be sure, does the collision mask object has a Platform behavior attached to it?

yes it does! as I said. it's only happening, I believe, on the same tiles that are rotated.

**Comment by D8H** [comment]
I can't reproduce the issue on my test project with rotated tiles.
Please can you send me a project to test (by email or discord if you don't want to share it publicly)?

**Comment by ajotanc** [comment]
> I can't reproduce the issue on my test project with rotated tiles. Please can you send me a project to test (by email or discord if you don't want to share it publicly)?

Link
https://liluo.io/games/4a0c9b9a-9201-4bef-b464-10e1417a16e7

**Comment by D8H** [comment]
> How do I generate the editable project link for you to have access?

You can zip the project folder.

**Comment by ajotanc** [comment]
> > How do I generate the editable project link for you to have access?
> 
> You can zip the project folder.

[gdevelop-game.zip](https://github.com/4ian/GDevelop/files/9633571/gdevelop-game.zip)

**Comment by D8H** [comment]
What happens is this:
- the character overlaps the jumpthru by left or right which is allowed.
- when a character is overlapping a jumpthru, they must not land on it. Which mean that the character falls.

The issue is that the 2 jumpthru are in the same object and considered as a whole.
A workaround is to use 2nd class for jumpthru platform to avoid a character to overlap one platform while landing on another one.
But, for your game, it seems that the character can't touch 2 platforms at once platforms so there might be something else.

**Comment by ajotanc** [comment]
What do you recommend me to do then? Because where I'm putting the jumpthru are in the branches of the trees.

**Comment by ajotanc** [comment]
> What do you recommend me to do then? Because where I'm putting the jumpthru are in the branches of the trees.



> What happens is this:
> 
> * the character overlaps the jumpthru by left or right which is allowed.
> * when a character is overlapping a jumpthru, they must not land on it. Which means that the character falls.
> 
> The issue is that the 2 jumpthru are in the same object and considered as a whole. A workaround is to use 2nd class for jumpthru platform to avoid a character to overlap one platform while landing on another one. But, for your game, it seems that the character can't touch 2 platforms at once platforms so there might be something else.

What do you recommend me to do then? Because where I'm putting the jumpthru are in the branches of the trees.

**Comment by D8H** [comment]
On the left there is more space than the character height between 2 platforms, so it works.
On the right, the character still overlaps one when it collides another and it go thought.

https://user-images.githubusercontent.com/2611977/191965194-2ad64f02-2e4c-471f-acf3-3acadd629481.mp4

The easy way is to make the character smaller enough. Otherwise, you'll need to duplicate tiles in the set to set a different class on them.

**Comment by D8H** [comment]
Also, may sure that your hitboxes are exactly aligned, because I guess that even less than 1 pixel difference will make the character overlaps them from left or right and fell.

![image](https://user-images.githubusercontent.com/2611977/191971752-f4be572a-4b45-4be2-a18b-2f37f57f2fde.png)

**Comment by ajotanc** [comment]
> Also, make sure that your hitboxes are exactly aligned, because I guess that even less than 1 pixel difference could make the character overlaps them from left or right and fell.

I understand thank you! I'll see what I can do and give an answer.

**Comment by ajotanc** [comment]
@D8H It worked, thank you very much! When possible, take a look at the other ticket I opened <3
