### ISSUE TITLE
[Question] code for toolbarIcon.js and applying a filter to the toolbar icons.

### ISSUE THREAD

**Issue by ValiantCuriosity** [4ian/GDevelop#738]
I have had the css working to change the toolbar icons for quite a few days, but I'm not still unable to understand how to use the ThemeConsumer in toolbar.js. I've tried using the sample code to figure it out for several days, but it just isn't working for me. Here is what works fine in toolbar.js. Of course, it changes all of the icons in every theme. It also does away with the grayscale. That isn't wanted. 

```
<IconButton
        {...otherProps}
        iconStyle={{
          //Properly align icons with the rest of the toolbar
          marginLeft: -4,
          marginTop: -4,

          //***/Change the icon color on the toolbar using a css filter***
          filter:this.props ? 'brightness(100%) sepia(1) hue-rotate(132deg) saturate(103.2%) drop-shadow(1px 1px 1px rgba(0,0,0,0.9))': undefined,
          //filter: this.props.disabled ? 'grayscale(100%)' : undefined,

        }}>
        <img title={tooltip} alt={tooltip} src={src} width={32} height={32} />
      </IconButton>
```

Next I tried to add/change the template that I was shown for correcting the background text color:

```
const toolbarIconStyle = (props: Props) => (
<ThemeConsumer>
{muiTheme => (
<span
style={{
...styles.toolbarIconStyle, //no idea what to do with this. I've tried all kinds of other options, but I'm lost.

...props.style,
}}

>
{props.children}
</span>
)}
</ThemeConsumer>
);
```
All I ever get are compile errors or things compile but I see the original blue icons. Can anyone help me? -R

**Comment by 4ian** [comment]
```
style={{
...styles.toolbarIconStyle, //no idea what to do with this. I've tried all kinds of other options, but I'm lost.

...props.style,
}}
```

So here this is an object with object spread operator: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax

If you want to use something from the theme, insert it into the style object:

```js
<ThemeConsumer>
{muiTheme => (
<span
style={{
...styles.toolbarIconStyle, //no idea what to do with this. I've tried all kinds of other options, but I'm lost.

...props.style,
filter: muiTheme.iconFilter
}}

>
{props.children}
</span>
)}
</ThemeConsumer>
```

You'll have to add iconFilter into the `theme` object (index.js inside DarkTheme/DefaultTheme).

> Of course, it changes all of the icons in every theme. 

If it's too complicated, don't lose time with this. Change it like you did for every theme. I'll take care of doing the proper modifications if you have at the end a theme that is visually pleasing.

> brightness(100%) sepia(1) hue-rotate(132deg) saturate(103.2%) drop-shadow(1px 1px 1px rgba(0,0,0,0.9))

That's a lot of filters! This might impact a bit performance, you should see if you can avoid the shadow or reduce the number of filters being used.

> It also does away with the grayscale

Change:

```
filter:this.props ? 'brightness(100%) sepia(1) hue-rotate(132deg) saturate(103.2%) drop-shadow(1px 1px 1px rgba(0,0,0,0.9))': undefined,
          //filter: this.props.disabled ? 'grayscale(100%)' : undefined,
```

to 

```
filter:this.props.disabled ? 'grayscale(100%)' : 'brightness(100%) sepia(1) hue-rotate(132deg) saturate(103.2%) drop-shadow(1px 1px 1px rgba(0,0,0,0.9))',
```

see? :) It's "is it disabled? If yes put the grayscale filter, otherwise the other filters".

As I said, technically the other filters should come from a color/parameter stored into the `theme` object. But if you struggle too much just hardcode it and I'll do the change if you have something that is interesting to add in GD :)

`ThemeConsumer` is a "Context" in React. It allow you to inject in a component an object (here, the theme object) without having to pass it as a prop. (Documentation is here: https://reactjs.org/docs/context.html) But you don't need to understand it: just add your variables into the `theme` and then push them in the `style` of the images :)

**Comment by ValiantCuriosity** [comment]
I can send you a screen grab of the theme. I think it will take me a year to understand how to apply the code to ToolbarIcon.js. I keep trying to “guess” how to redo the syntax from what you showed me:

const BackgroundText = (props: Props) => (
<ThemeConsumer>
{muiTheme => (
<span
style={{
...styles.messageStyle,
color: muiTheme.emptyMessage.textColor,
textShadow: `1px 1px 0px ${muiTheme.emptyMessage
.shadowColor}`,
...props.style,
}}
title={props.tooltipText}
>
{props.children}
</span>
)}
</ThemeConsumer>
);

Your example helped me to replace the text color easily, but I just can’t seem to make the transition for the icons. I think I need to learn React. The way I code, it will take me forever. LOL

As always, I appreciate the way you try to help ’the ignorant’. ;-)
-Rachel

**Comment by ValiantCuriosity** [comment]
Let’s try this again:

In my new theme’s index.js, I put the following:

const toolbarIconColor = 'filter:this.props.disabled ? grayscale(100%) : brightness(100%) sepia(1) hue-rotate(132deg) saturate(103.2%) drop-shadow(1px 1px 1px rgba(0,0,0,0.9))’; //add the const above with the others

Then I add this to the “theme object”:
const theme: Theme = {
  fontFamily: '-apple-system, BlinkMacSystemFont, sans-serif', //OS X font
  palette: {
    primary1Color: blue,
    primary2Color: blue,
    accent1Color: almostWhite,
    canvasColor,
    textColor: lightWhite,
    secondaryTextColor: notSoWhite,
    alternateTextColor: '#444',
    borderColor: '#444444',
    disabledColor: '#888888',
    pickerHeaderColor: '#444444',
    clockCircleColor: '#444444',
    toolbarIcon:toolbarIconColor ,//this is what I add. Is this correct? If not, what should it look like?
  },

Next, I need to add the ThemeConsurmer code into ToolbarIcon.js. 

What should this code be?? Can you show me the entire code to add to the ToolbarIcon.js

TIA -R

**Comment by 4ian** [comment]
> const toolbarIconColor = 'filter:this.props.disabled ? grayscale(100%) : brightness(100%) sepia(1) hue-rotate(132deg) saturate(103.2%) drop-shadow(1px 1px 1px rgba(0,0,0,0.9))’; //add the const above with the others

You're putting JavaScript code in a string, that won't work ;)

Inside the theme `index.js` file:

```js
// ...

const theme = {
  ...
  toolbarIconFilter: 'brightness(100%) sepia(1) hue-rotate(132deg) saturate(103.2%) drop-shadow(1px 1px 1px rgba(0,0,0,0.9))',
};
```

Inside `ToolbarIcon.js`:
```js
import React, { Component } from 'react';
import IconButton from 'material-ui/IconButton';
import ThemeConsumer from '../UI/Theme/ThemeConsumer';


export default class ToolbarIcon extends Component {
  render() {
    const { src, tooltip, ...otherProps } = this.props;

    return (
      <ThemeConsumer>
        {muiTheme => (
          <IconButton
            {...otherProps}
            iconStyle={{
              //Properly align icons with the rest of the toolbar
              marginLeft: -4,
              marginTop: -4,
              filter: this.props.disabled ? 'grayscale(100%)' : muiTheme.toolbarIconFilter,
            }}
          >
            <img title={tooltip} alt={tooltip} src={src} width={32} height={32} />
          </IconButton>
        )}
      </ThemeConsumer>
    );
  }
}
```

Done :) (in theory, you also have to add `toolbarIconFilter: ""` to other themes for consistency)

![image](https://user-images.githubusercontent.com/1280130/48374834-e7628100-e6bd-11e8-89b1-92f9324d494f.png)

My advice is to check carefully what every object is, what it represents. If you're unfamiliar with the way React is written, it's a good idea indeed to check a tutorial or too. It's not complicated, React is 100% JavaScript with the special notation "JSX" that allow to write components like HTML. But JavaScript has a lot of new "features" like object spread (the `...something` that you see like `{...otherProps}`) or the arrow functions being used inside ThemeConsumer which can be a bit surprising. Once you'll get used to it and understand how it works, it will be easy - everything is just JavaScript :)

**Comment by ValiantCuriosity** [comment]
Thanks Florian,

I’ll try some more and see. Otherwise, I’ll just try to send you what I have done. I was thinking that if I could once get the code, I could then design more themes. That would be fun, but the coding is not easy. I only know a little javascript. I’m not a good coder. Probably cobble most stuff together using free code that does what I need it to do. I highly respect people who are talented coders. You are one. ;-)

-R

**Comment by 4ian** [comment]
With this you should at least be able to customize toolbar icons per theme :) For other icons I can take care of adding this to the theme.
Changing theme is ok as long as you don't have to dive too much into how it's used - at which point you surely need a better understanding of React and JavaScript.

Experience and practice will make things better and easier to understand ;) It's always hard at the beginning because there is a lot to learn.

**Comment by ValiantCuriosity** [comment]
Well, it does now recognize the toolbarIconFilter in the index.js. The problem is that it works the same as when the filter is put directly into the IconButton Style. It changes all of the themes. Not just the “Forest” theme. When I select the defaultTheme, it doesn’t display the blue icons. It displays my gradient filter icons.

I copied and pasted the exact code that you sent and it still doesn’t work for me. I think this is just more than I should try to do. I like themes to be congruent across the app. That is, if my colors are various shades of some color, I want all of the icons, background colors, etc to match. Maybe, eventually, you will be able to add the ability to change everything in a new theme, but for now, it is a little too much for me. I’ll just try to figure out a new color theme that works with what you already have for icons, etc. 

The good news is that I did add some documentation to docuwiki about themes. It is in “Other Features”. It doesn’t show up in menu list so I need to figure out how to do that, but it does show when people click on the “Other Features” title. The docs deal with how to change a theme based on the files in a copied theme so there isn’t anything about the icons or background text. ;-)

Thank you again for all of your help. I have appreciated your patience, but I think it is time for me to step back and just work within the boundaries of what has been defined in the theme files. I understand that. 

-R

**Comment by 4ian** [comment]
As you prefer, I'll check if I can add support for tweaking the icons colors by myself in the next days though. Could be a cool feature for making new themes :)

I'll keep you updated here if I add this. Created a card for it on the roadmap: https://trello.com/c/IDDDcUmr/187-add-support-for-customizing-the-toolbar-and-project-manager-icons-color-in-themes

Thanks for the updates on the wiki, I'll read this! :)

**Comment by 4ian** [comment]
I've made the changes here: https://github.com/4ian/GDevelop/commit/eefc656d49e49b028f8fce17d64710e77066bfe8

You can pull to get the latest version on master (or restart from scratch by following again the README). Also be sure to remove newIDE/app/public/libGD.js file and then starting the editor (npm start or yarn start as explained in the README).

There is a new variable `gdevelopIconsCSSFilter: ''` where you can set a CSS filter to apply to (non disabled) icons.
Be sure to use 1/2 filter max to keep good performances :)

**Comment by ValiantCuriosity** [comment]
Wow! Fast. Thank you. I’ll try to tackle this today. I’ve been also attempting to get my brain around a little bit of React. ;-)

-R

**Comment by ValiantCuriosity** [comment]
It's working! :-D 

Now, I will study the way that you changed it. Maybe I can figure out how to do some other things. 

Thanks again,
-R

**Comment by ValiantCuriosity** [comment]
Can you tell me where colors of groups, comments, text colors are located. I just want to look at the code. I understand that I can’t change these but it would be fun to look. I can’t find them.

Thank you,
-R

**Comment by ValiantCuriosity** [comment]
OK, now I’ve noticed that the toolbar icons on the top right will change after I click on some feature within the area. ie, a tab, an Event action, etc. 

In the Events Editor, I can’t theme the dropdown background or text color that is shown when an object in an action is clicked.

Is there some way to find all of these various theme references easily and without cluttering up your github asking about them? You find them and link to them so quickly. :-)

I've applied a filter to the small event editor icons, but I wonder if the process for making the icons change only in the designated theme and not throughout all themes is  by using the ThemeConsumer as you recommended for the toolbar icons.

It seems like your toolbar icon changes were pretty extensive. I looked at the files and code where you made the changes. It is WAY over my head so if I need to dig into many files and changes, I don’t want to think about trying to use ThemeConsumer for this. (I may need to take a long vacation and try to learn React and brush up some more on javascript.)

When I started this, I thought it would be a fairly simple matter. If I just stay within the Theme files, it is, but I’m kind of picky. I like to manipulate and match everything in the scene. I wanted to dig into all the icons, text color, comment colors, and so forth. 

I do agree with you 100% that your time is better spent on developing features for GD. Themes are something that most people probably wouldn’t even use. 

TIA for all of your help, support and for GD itself. It is a phenomenal piece of work.
-R

**Comment by 4ian** [comment]
> When I change the theme, say from myTheme back to defaultTheme, the right toolbar icons do not register the change until I refresh the entire GD application. Maybe I’m doing something wrong… or maybe there is a step that I am missing?

No you're doing things right, it's a shortcoming in GD.

> I've applied a filter to the small event editor icons, but I wonder if the process for making the icons change only in the designated theme and not throughout all themes is  by using the ThemeConsumer as you recommended for the toolbar icons.

Yes, same thing should be done here to have them customized per theme.
Let's try for now to make themes without this change :) If it turns out that it is significantly better looking with a filter, I'll do the changes to have a filter there too.
